version: '3.7'

services:
  swift-todo:
    container_name: swift-todo
    build:
      context: ./swift
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./swift:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
